// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/pdcgo/accounting_service"
	"github.com/pdcgo/shared/configs"
)

// Injectors from wire.go:

func InitializeMigration() (*Migration, error) {
	appConfig, err := configs.NewProductionConfig()
	if err != nil {
		return nil, err
	}
	db, err := NewDatabase(appConfig)
	if err != nil {
		return nil, err
	}
	accountingSetupServiceClient := NewSetupClient(appConfig)
	migrationHandler := accounting_service.NewMigrationHandler(db)
	migration := NewMigration(db, accountingSetupServiceClient, migrationHandler)
	return migration, nil
}
